name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_NAME }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - run: |
          docker build . -t ${{ secrets.ACR_NAME }}/plainbcntrainingsapi:${{ github.sha }} -t ${{ secrets.ACR_NAME }}/plainbcntrainingsapi:latest
          docker push ${{ secrets.ACR_NAME }}/plainbcntrainingsapi:latest
          docker push ${{ secrets.ACR_NAME }}/plainbcntrainingsapi:${{ github.sha }}
          
      - uses: azure/webapps-deploy@v2
        with:
          app-name: '${{ secrets.AZURE_WEBAPP_NAME }}'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISHPROFILE }}
          images: '${{ secrets.ACR_NAME }}/plainbcntrainingsapi:${{ github.sha }}'
